
---
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    numbered_sections: true
---

# Struktur Penulisan Panduan Praktik Klinis

Panduan ini memuat pengelolaan penyakit mulai dari penjelasan hingga
penatalaksanaan penyakit tersebut. Panduan Praktik Klinis (PPK) Dokter
Pelayanan Primer disusun berdasarkan pedoman yang berlaku secara global yang
dirumuskan bersama perhimpunan profesi dan Kementerian Kesehatan.

# Judul Penyakit {.tabset .tabset-fade}

Judul penyakit berdasarkan daftar penyakit terpilih di SKDI 2012, namun
beberapa penyakit dengan karakteristik yang hampir sama dikelompokkan menjadi
satu judul penyakit. 

Pada setiap judul penyakit dilengkapi:

## Kode penyakit

* Kode *International Classification of Primary Care* (ICPC), menggunakan kode
	ICPC-2 untuk diagnosis 
* Kode *International Classification of Disease* (ICD), menggunakan kode ICD-10
	versi 10.

Penggunaan kode penyakit untuk pencatatan dan pelaporan di fasiitas
pelayanan kesehatan primer mengacu pada ketentuan peraturan perundangan yang
berlaku

## Kompetensi Dokter

Tingkat kemampuan dokter dalam penatalaksanaan penyakit berdasarkan Peraturan
Konsil Kedokteran Indonesia Nomor 11 tahun 2012 tentang Standar Kompetensi
Dokter Indonesia.

# Masalah Kesehatan

Masalah kesehatan berisi pengertian singkat serta prevalensi penyakit di
Indonesia. Substansi dari bagian ini diharapkan dapat memberikan pengetahuan
awal serta gambaran kondisi yang mengarah kepada penegakan diagnosis penyakit
tersebut.

# Hasil Anamnesis (*Subjective*)

Hasil Anamnesis berisi keluhan utama maupun keluhan penyerta yang sering
disampaikan oleh pasien atau keluarga pasien. Penelusuran riwayat penyakit yang
diderita saat ini, pennyakit lainnya yang merupakan faktor risiko, riwayat
keluarga, riwayat sosial, dan riwayat alergi menjadi informasi lainnya pada
bagian ini. Pada beberapa penyakit, bagian ini memuat informasi spesifik yang
harus diperoleh dokter dari pasien atau keluarga pasien untuk menguatkan
diagnosis penyakit.

# Hasil Pemeriksaan Fisik dan Pemeriksaan Penunjang Sederhana (*Objective*)

Bagian ini berisi hasil pemeriksaan fisik dan pemeriksaan penunjang yang
spesifik, mengarah kepada diagnosis penyakit (*pathognomonis*). Meskipun tidak
memuat rangkaian pemeriksaan fisik lainnya, pemeriksaan tanda vital dan
pemeriksaan fisik menyeluruh tetap harus dilakukan oleh dokter layanan primer
untuk memastikan diagnosis serta menyingkirkan diagnosis banding.

# Penegakan Diagnosis (*Assessment*)

Bagian ini berisi diagnosis yang sebagian besar dapat ditegakkan dengan
anamnesis dan pemeriksaan fisik. Beberapa penyakit membutuhkan hasil
pemeriksaan penunjang untuk memastikan diagnosis atau karena telah menjadi
standar algoritma penegakan diagnosis. Selain itu, bagian ini juga memuat
klasifikasi penyakit, diagnosa banding, dan komplikasi penyakit.

# Rencana Penatalaksanaan Komprehensif (*Plan*) 

Bagian ini berisi sistematika rencana penatalaksanaan berorientasi pada pasien
(*patient centered) yang terbagi atas dua bagian yaitu penatalaksanaan non
farmakologi dan farmakologi. Selain itu, bagian ini juga berisi edukasi dan
konseling terhadap pasien dan keluarga (*family focus*), aspek komunitas
lainnya (*community oriented*) serta kapan dokter perlu merujuk pasien (kriteria
rujukan).

Dokter akan merujuk pasien apabila memenuhi salah satu dari kriteria "TACC" (*Time-Age-Complication-Comorbidity*) berikut:

1. *Time*: Jika perjalanan penyakit dapat digolongkan kepada kondisi kronisatau
	 melewati *Golden Time Standard*.
2. *Age*: Jika usia pasien masuk dalam kategori yang dikhawatirkan
	 meninngkatkan risiko komplikasi serta risiko kondisi penyakit lebih berat.
3. *Complication*: Jika komplikasi yang ditemui dapat memperberat kondisi
	 pasien.
4. *Comorbidity*: Jika terdapat keluhan atau gejala penyakit lain yang
	 memperberat kondisi pasien

Selain empat kriteria di atas, kondisi fasilitas pelayanan juga dapat menjadi
dasar bagi dokter untuk melakukan rujukan demi menjamin keberlangsungan
penatalaksanaan dengan persetujuan pasien.

# Peralatan

Bagian ini berisi komponen fasilitas pendukung spesifik dalam penegakan
diagnosis dan penatalaksanaan penyakit tersebut. Penyeiaan peralatan tersebut
merupakan kewajiban fasilitas pelayanan kesehatan disamping peralatan medik
wajib untuk pemeriksaan umum tanda vital.

# Prognosis

Kategori prognosis sebagai berikut:

1. *Ad vitam*, menunjuk pada pengaruh penyakit terhadap proses kehidupan.
2. *Ad functionam*, menunjuk pada pengaruh penyakit terhadap fungsi organ atau
   fungsi manusia dalam melakukan tugasnya.
3. *Ad sanationam*, menunjuk pada penyakit yang dapat sembuh total sehingga
   dapat beraktivitas seperti biasa.

Prognosis digolongkan sebagai berikut:

1. *Sanam*: sembuh
2. *Bonam*: baik
3. *Malam*: buruk/jelek
4. *Dubia*: tidak tentu/ragu-ragu
5. *Dubia ad sanam*: tidak tentu/ragu-ragu, cenderung sembuh/baik
6. *Dubia ad malam*: tidak tentu/ragu-ragu, cenderung memburuk/jelek

Untuk penentuan prognosis sangat ditentukan dengan kondisi pasien saat
dompetensi Dokter Indonesia.
