
---
author: <++>
title: <++>
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    collapsed: false
    smooth_scroll: true
    df_print: paged
  pdf_document:
    number_sections: true
    df_print: kable
    highlight: tango
  slidy_presentation:
    highlight: tango
bibliography: ref.bib
csl: $HOME$/.pandoc/vancouver-superscript.csl
---

<++>
3. Hordeolum
No. ICPC-2
No. ICD-10
Tingkat Kemampuan

: F72 Blepharitis/stye/chalazion
: H00.0 Hordeolum and other deep inflammation of
eyelid
: 4A

## Masalah Kesehatan

Hordeolum adalah peradangan supuratif kelenjar kelopak mata. Biasanya
merupakan infeksi Staphylococcus pada kelenjar sebasea kelopak. Dikenal
dua bentuk hordeolum internum dan eksternum. Hordeolum eksternum
merupakan infeksi pada kelenjar Zeiss atau Moll. Hordeolum internum
merupakan infeksi kelenjar Meibom yang terletak di dalam tarsus. Hordeolum
mudah timbul pada individu yang menderita blefaritis dan konjungtivitis
menahun.
## Hasil Anamnesis (Subjective)

Keluhan
Pasien datang dengan keluhan kelopak yang bengkak disertai rasa sakit.
Gejala utama hordeolum adalah kelopak yang bengkak dengan rasa sakit dan
mengganjal, merah dan nyeri bila ditekan, serta perasaan tidak nyaman dan
sensasi terbakar pada kelopak mata
## Hasil Pemeriksaan Fisik dan Penunjang Sederhana (Objective)

Pemeriksaan Fisik Oftalmologis
Ditemukan kelopak mata bengkak, merah, dan nyeri pada perabaan. Nanah
dapat keluar dari pangkal rambut (hordeolum eksternum). Apabila sudah
terjadi abses dapat timbul undulasi.
Pemeriksaan Penunjang
Tidak diperlukan
## Penegakan Diagnostik (Assessment)

Diagnosis Klinis
Penegakan diagnosis dengan anamnesis dan pemeriksaan fisik.

166

Diagnosis Banding
1. Selulitis preseptal
2. Kalazion
3. Granuloma piogenik
Komplikasi
1. Selulitis palpebra
2. Abses palpebra
## Penatalaksanaan Komprehensif (Plan)

Penatalaksanaan
1. Mata dikompres hangat 4-6 kali sehari selama 15 menit setiap kalinya
untuk membantu drainase. Tindakan dilakukan dengan mata tertutup.
2. Kelopak mata dibersihkan dengan air bersih atau pun dengan sabun atau
sampo yang tidak menimbulkan iritasi, seperti sabun bayi. Hal ini dapat
mempercepat proses penyembuhan. Tindakan dilakukan dengan mata
tertutup.
3. Jangan menekan atau menusuk hordeolum, hal ini dapat menimbulkan
infeksi yang lebih serius.
4. Hindari pemakaian make-up pada mata, karena kemungkinan hal itu
menjadi penyebab infeksi.
5. Jangan memakai lensa kontak karena dapat menyebarkan infeksi ke
kornea.
6. Pemberian terapi topikal dengan Oxytetrasiklin salep mata atau
kloramfenikol salep mata setiap 8 jam. Apabila menggunakan
kloramfenikol tetes mata sebanyak 1 tetes tiap 2 jam.
7. Pemberian terapi oral sistemik dengan Eritromisin 500 mg pada dewasa
dan anak sesuai dengan berat badan atau Dikloksasilin 4 kali sehari
selama 3 hari.
Pemeriksaan Penunjang Lanjutan
Tidak diperlukan
Konseling & Edukasi
Penyakit hordeolum dapat berulang sehingga perlu diberi tahu pasien dan
keluarga untuk menjaga higiene dan kebersihan lingkungan.
Rencana Tindak Lanjut
Bila dengan pengobatan konservatif tidak berespon dengan baik, maka
prosedur pembedahan mungkin diperlukan untuk membuat drainase pada
hordeolum.
Kriteria rujukan
1. Bila tidak memberikan respon dengan pengobatan konservatif
2. Hordeolum berulang

167

Peralatan
Peralatan bedah minor
Prognosis
1. Ad vitam
2. Ad functionam
3. Ad sanationam

: Bonam
: Bonam
: Bonam

Referensi
1. Gondhowiardjo, T.D. Simanjuntak, G. Panduan Manajemen Klinis
th
Perdami, 1 Ed. Jakarta: CV Ondo. 2006.
2. Riordan, Paul E. Whitcher, John P. Vaughan & Asbury Oftalmologi Umum.
Edisi 17. Jakarta: EGC. 2009.
3. Sidarta, I. Ilmu Penyakit Mata. Edisi III. Cetakan V. Jakarta:Balai Penerbit
FK UI. 2008.
4. Vaughan, D.G. Oftalmologi Umum. Edisi 14. Cetakan I. Jakarta: Widya
Medika. 2000.
