
---
author: <++>
title: <++>
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    collapsed: false
    smooth_scroll: true
    df_print: paged
  pdf_document:
    number_sections: true
    df_print: kable
    highlight: tango
  slidy_presentation:
    highlight: tango
bibliography: ref.bib
csl: $HOME$/.pandoc/vancouver-superscript.csl
---

<++>
Astigmatisme

No. ICPC-2
No. ICD-10
Tingkat Kemampuan

: F91 Refractive error
: H52.2 Astigmatisme
: 4A

## Masalah Kesehatan

Astigmatisme adalah keadaan di mana sinar sejajar tidak dibiaskan pada satu
titik fokus yang sama pada semua meridian. Hal ini disebabkan oleh
kelengkungan kornea atau lensa yang tidak sama pada berbagai meridian.
## Hasil Anamnesis (Subjective)

Keluhan
Pasien biasanya datang dengan keluhan penglihatan kabur dan sedikit distorsi
yang kadang juga menimbulkan sakit kepala. Pasien memicingkan mata, atau
head tilt untuk dapat melihat lebih jelas.

177

## Hasil Pemeriksaan Fisik dan Penunjang Sederhana (Objective)

Pemeriksaan Fisik
Keadaan umum biasanya baik.
Pemeriksaan visus dengan Snellen Chart akan menunjukkan tajam
penglihatan tidak maksimal dan akan bertambah baik dengan pemberian
pinhole.
## Penegakan Diagnostik (Assessment)

Diagnosis Klinis
Penegakan diagnosis dilakukan berdasarkan anamnesis dan pemeriksaan
refraksi. Tajam penglihatan akan mencapai maksimal dengan pemberian lensa
silindris.
Diagnosis Banding
Kelainan refraksi lainnya.
## Penatalaksanaan Komprehensif (Plan)

Penatalaksanaan
Penggunaan kacamata lensa silindris dengan koreksi yang sesuai.
Pemeriksaan Penunjang Lanjutan
Tidak diperlukan.
Konseling dan Edukasi
Memberitahu keluarga bahwa astigmatisma merupakan gangguan penglihatan
yang dapat dikoreksi.
Kriteria Rujukan
Pasien perlu dirujuk ke layanan sekunder bila:
1. koreksi dengan kacamata tidak memperbaiki visus, atau
2. ukuran lensa tidak dapat ditentukan (misalnya astigmatisme berat).
Peralatan
1. Snellen Chart
2. Satu set lensa coba (trial frame dan trial lenses)
3. Pinhole
Prognosis
1. Ad vitam
2. Ad functionam
3. Ad sanationam

: Bonam
: Bonam
: Bonam

178

Referensi
1. Gerhard, K.L. Oscar, Gabriele. Doris, Peter. Ophtalmology a short
nd
textbook. 2 Ed. New York. Thieme Stuttgart. 2007.
2. Gondhowiardjo, T.D. Simanjuntak, G. Panduan Manajemen Klinis
th
Perdami, 1 Ed. Jakarta: CV Ondo. 2006.
3. James, Brus.dkk. Lecture Notes Oftalmologi. Erlangga. Jakarta. 2005.
4. Riordan. Paul, E. Whitcher, John P. Vaughan & Asbury Oftalmologi Umum.
Ed 17. Jakarta: EGC. 2009.
5. Sidarta, I. Ilmu Penyakit Mata. Edisi III. Cetakan V. Jakarta: Balai Penerbit
FK UI. 2008.
6. Vaughan, D.G. Oftalmologi Umum. Ed 14. Cetakan I. Jakarta: Widya
Medika. 2000.
