
---
author: <++>
title: <++>
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    collapsed: false
    smooth_scroll: true
    df_print: paged
  pdf_document:
    number_sections: true
    df_print: kable
    highlight: tango
  slidy_presentation:
    highlight: tango
bibliography: ref.bib
csl: $HOME$/.pandoc/vancouver-superscript.csl
---

<++>
12. Katarak pada Pasien Dewasa
No. ICPC-2
No. ICD-10
Tingkat Kemampuan

: F92 Cataract
: H26.9 Cataract, unspecified
:2

## Masalah Kesehatan

Katarak adalah kekeruhan pada lensa yang menyebabkan penurunan tajam
penglihatan (visus). Katarak paling sering berkaitan dengan proses degenerasi
lensa pada pasien usia di atas 40 tahun (katarak senilis). Selain katarak
senilis, katarak juga dapat terjadi akibat komplikasi glaukoma, uveitis, trauma

184

mata, serta kelainan sistemik seperti diabetes mellitus, riwayat pemakaian obat
steroid, dan lain-lain. Katarak biasanya terjadi bilateral, namun dapat juga
pada satu mata (monokular).
## Hasil Anamnesis (Subjective)

Keluhan
Pasien datang dengan keluhan penglihatan menurun secara perlahan seperti
tertutup asap/kabut. Keluhan disertai ukuran kacamata semakin bertambah,
silau, dan sulit membaca.
Faktor Risiko
1. Usia lebih dari 40 tahun
2. Riwayat penyakit sistemik, seperti diabetes mellitus
3. Pemakaian tetes mata steroid secara rutin
4. Kebiasaan merokok dan pajanan sinar matahari
## Hasil Pemeriksaan Fisik dan Penunjang Sederhana (Objective)

Pemeriksaan Fisik
1. Visus menurun yang tidak membaik dengan pemberian pinhole
2. Pemeriksaan shadow test positif
3. Terdapat kekeruhan lensa yang dapat dengan jelas dilihat dengan teknik
pemeriksaan jauh (dari jarak 30 cm) menggunakan oftalmoskop sehingga
didapatkan media yang keruh pada pupil. Teknik ini akan lebih mudah
dilakukan setelah dilakukan dilatasi pupil dengan tetes mata Tropikamid
0.5% atau dengan cara memeriksa pasien pada ruang gelap.
Pemeriksaan Penunjang
Tidak diperlukan.
## Penegakan Diagnostik (Assessment)

Diagnosis Klinis
Penegakan diagnosis dilakukan berdasarkan anamnesis dan pemeriksaan
visus dan pemeriksaan lensa
Komplikasi
Glaukoma dan uveitis
## Penatalaksanaan Komprehensif (Plan)

Penatalaksanaan
Pasien dengan katarak yang telah menimbulkan gangguan penglihatan yang
signifikan dirujuk ke layanan sekunder yang memiliki dokter spesialis mata
untuk mendapatkan penatalaksanaan selanjutnya. Terapi definitif katarak
adalah operasi katarak.

185

Konseling & Edukasi
1. Memberitahu keluarga bahwa katarak adalah gangguan penglihatan yang
dapat diperbaiki.
2. Memberitahu keluarga untuk kontrol teratur jika sudah didiagnosis katarak
agar tidak terjadi komplikasi.
Kriteria Rujukan
1. Katarak matur
2. Jika pasien telah mengalami gangguan penglihatan yang signifikan
3. Jika timbul komplikasi
Peralatan
1.
2.
3.
4.

Senter
Snellen chart
Tonometri Schiotz
Oftalmoskop

Prognosis
1. Ad vitam
2. Ad functionam
3. Ad sanationam

: Bonam
: Dubia ad bonam
: Dubia ad bonam

Referensi
1. Gerhard, K.L. Oscar, Gabriele. Doris, Peter. Ophtalmology a short
nd
textbook. 2 Ed. New York: Thieme Stuttgart. 2007.
2. Gondhowiardjo, T.D. Simanjuntak, G. Panduan Manajemen Klinis
th
Perdami, 1 Ed.Jakarta: CV Ondo. 2006.
3. James, Brus. dkk. Lecture Notes Oftalmologi. Jakarta: Erlangga. 2005.
4. Riordan, P.E, Whitcher, J.P. Vaughan & Asbury Oftalmologi Umum.
Ed17.Jakarta: EGC. 2009.
5. Sidarta, I. Ilmu Penyakit Mata, Ed III. Cetakan V. Jakarta: Balai Penerbit
FK UI. 2008.
6. Vaughan, D.G. Oftalmologi Umum. Edisi 14. Cetakan I. Jakarta: Widya
Medika. 2000.
