
---
author: <++>
title: <++>
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    collapsed: false
    smooth_scroll: true
    df_print: paged
  pdf_document:
    number_sections: true
    df_print: kable
    highlight: tango
  slidy_presentation:
    highlight: tango
bibliography: ref.bib
csl: $HOME$/.pandoc/vancouver-superscript.csl
---

<++>
14. Glaukoma Kronis
No. ICPC-2
No. ICD-10
Tingkat Kemampuan

: F93 Glaucoma
: H40.2 Primary angle-closure glaucoma
: 3B

## Masalah Kesehatan

Glaukoma adalah kelompok penyakit mata yang umumnya ditandai kerusakan
saraf optik dan kehilangan lapang pandang yang bersifat progresif serta
berhubungan dengan berbagai faktor risiko terutama tekanan intraokular (TIO)
yang tinggi. Glaukoma merupakan penyebab kebutaan kedua terbesar di dunia
setelah katarak. Kebutaan karena glaukoma tidak bisa disembuhkan, tetapi
pada kebanyakan kasus glaukoma dapat dikendalikan. Umumnya penderita
glaukoma telah berusia lanjut, terutama bagi yang memiliki risiko. Hampir
separuh penderita glaukoma tidak menyadari bahwa mereka menderita
penyakit tersebut.
## Hasil Anamnesis (Subjective)

Keluhan
Pasien datang dengan keluhan yang bervariasi dan berbeda tergantung jenis
glaukoma.
Glaukoma kronis dapat dibagi menjadi glaukoma kronis primer dan sekunder.
1. Umumnya pada fase awal, glaukoma kronis tidak menimbulkan keluhan,
dan diketahui secarakebetulan bila melakukan pengukuran TIO
2. Mata dapat terasa pegal, kadang-kadang pusing
3. Rasa tidak nyaman atau mata cepat lelah
4. Mungkin ada riwayat penyakit mata, trauma, atau pemakaian obat
kortikosteroid
5. Kehilangan lapang pandang perifer secara bertahap pada kedua mata

189

6. Pada glaukoma yang lanjut dapat terjadi penyempitan lapang pandang
yang bermakna hingga menimbulkan gangguan, seperti menabrak-nabrak
saat berjalan.
Faktor Risiko
1. Usia 40 tahun atau lebih
2. Ada anggota keluarga menderita glaukoma
3. Penderita miopia, penyakit kardiovaskular, hipertensi, hipotensi,
vasospasme, diabetes mellitus, dan migrain
4. Pada glaukoma sekunder, dapat ditemukan riwayat pemakaian obat
steroid secara rutin, atau riwayat trauma pada mata.
## Hasil Pemeriksaan Fisik dan Penunjang Sederhana (Objective)

Glaukoma adalah penyakit mata yang ditandai oleh trias glaukoma, yang terdiri
dari:
1. Peningkatan tekanan intraokular
2. Perubahan patologis pada diskus optikus
3. Defek lapang pandang yang khas.
Pemeriksaan Oftalmologis
1. Visus normal atau menurun
2. Lapang pandang menyempit pada tes konfrontasi
3. Tekanan intra okular meningkat
4. Pada funduskopi, rasio cup / disc meningkat (rasio cup / disc normal: 0.3)

Gambar 4. 4. Kelainan diskus optik akibat komplikasi glaukoma
Pemeriksaan Penunjang
Tidak dilakukan pada pelayanan primer.
## Penegakan Diagnostik (Assessment)

Diagnosis Klinis
Penegakan diagnosis dilakukan berdasarkan anamnesis dan pemeriksaan
oftalmologis.

190

Diagnosis Banding:
1. Katarak
2. Kelainan refraksi
3. Retinopati diabetes / hipertensi
4. Retinitis pigmentosa
## Penatalaksanaan Komprehensif (Plan)

Penatalaksanaan
Penatalaksanaan kasus glaukoma pada layanan primer bertujuan
mengendalikan tekanan intra okuler dan merujuk ke dokter spesialis mata di
rumah sakit.
Pengobatan umumnya medikamentosa dengan obat-obat glaukoma,
contohnya Timolol 0.5%, 2 x 1 tetes/hari. Jenis obat lain dapat diberikan bila
dengan 1 macam obat TIO belum terkontrol
Konseling dan Edukasi
1. Memberitahu keluarga bahwa kepatuhan pengobatan sangat penting untuk
keberhasilan pengobatan glaukoma.
2. Memberitahu pasien dan keluarga agar pasien dengan riwayat glaukoma
pada keluarga untuk memeriksakan matanya secara teratur.
Kriteria Rujukan
Pada glaukoma kronik, rujukan dilakukan segera setelah penegakan
diagnosis.
Peralatan
1. Snellen chart
2. Tonometer Schiotz
3. Oftalmoskop
Prognosis
1. Ad vitam
2. Ad functionam
3. Ad sanationam

: Bonam
: Dubia ad malam
: Dubia ad malam

Referensi
1. Gerhard, K.L. Oscar, Gabriele. Doris, Peter. Ophtalmology a short
nd
textbook. 2 Ed. New York: Thieme Stuttgart. 2007.
2. Gondhowiardjo, T.D. Simanjuntak, G. Panduan Manajemen Klinis
th
Perdami, 1 Ed.Jakarta: CV Ondo. 2006.
3. James, Brus. dkk. Lecture Notes Oftalmologi. Jakarta: Erlangga. 2005.
4. Riordan, P.E, Whitcher, J.P. Vaughan & Asbury Oftalmologi Umum.
Ed17.Jakarta: EGC. 2009.
5. Sidarta, I. Ilmu Penyakit Mata, Ed III. Cetakan V. Jakarta: Balai Penerbit
FK UI. 2008.

191

6. Vaughan, D.G. Oftalmologi Umum. Edisi 14. Cetakan I. Jakarta: Widya
Medika. 2000.
7. Sumber Gambar: http://www.onmedica.com/
