
---
author: <++>
title: <++>
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    collapsed: false
    smooth_scroll: true
    df_print: paged
  pdf_document:
    number_sections: true
    df_print: kable
    highlight: tango
  slidy_presentation:
    highlight: tango
bibliography: ref.bib
csl: $HOME$/.pandoc/vancouver-superscript.csl
---

<++>
18.

Laserasi kelopak mata

No. ICPC-2
No. ICD-10
Tingkat Kemampuan

: F79 Injury eye other
: S01.1Open wound of eyelid and periocular area
: 3B

## Masalah Kesehatan

Laserasi kelopak adalah terpotongnya jaringan pada kelopak mata. Penyebab
laserasi kelopak dapat berupa sayatan benda tajam, trauma tumpul
(kecelakaan lalu lintas atau olahraga), maupun gigitan hewan. Laserasi pada
kelopak perlu ditangani segera agar fungsi dan kosmetik kelopak dapat
dipertahankan.
## Hasil Anamnesis (Subjective)

Keluhan
1. Terdapat rasa nyeri periorbita
2. Perdarahan dan bengkak pada kelopak

199

3. Mata berair
4. Tidak terdapat penurunan tajam penglihatan bila cedera tidak melibatkan
bola mata
Faktor Risiko
Terdapat riwayat trauma tajam maupun tumpul
## Hasil Pemeriksaan Fisik dan Penunjang Sederhana (Objective)

Pemeriksaan Fisik
1. Pemeriksaan refleks pupil dan tajam penglihatan
2. Pemeriksaan mata dengan lup dan senter untuk mengidentifikasi:
a. Luas dan dalamnya laserasi pada kelopak, termasuk identifikasi
keterlibatan tepi kelopak, kantus medial atau kantus lateral. Pemeriksa
dapat menggunakan lidi kapas selama pemeriksaan.
b. Adanya benda asing
c. Keterlibatan bola mata
Pemeriksaan Penunjang
Tidak diperlukan
## Penegakan Diagnostik (Assessment)

Diagnosis Klinis
Diagnosis ditegakkan melalui anamnesis dan pemeriksaan fisik.
Diagnosis banding
Tidak ada
Komplikasi
Trauma pada sistem lakrimal
## Penatalaksanaan Komprehensif (Plan)

Penatalaksanaan
1. Bersihkan luka apabila diyakini bola mata intak
2. Pertimbangkan pemberian profilaksis tetanus
3. Berikan antibiotik sistemik
4. Segera rujuk ke dokter spesialis mata untuk mendapatkan penanganan
secepatnya
Konseling dan Edukasi
1. Memberitahu pasien bahwa luka pada kelopak perlu menjalani
pembedahan (menutup luka)
2. Menggunakan alat / kacamata pelindung pada saat bekerja atau
berkendara.
3. Anjurkan pasien untuk kontrol bila keluhan bertambah berat setelah
dilakukan tindakan, seperti mata bertambah merah, bengkak atau disertai
dg penurunan visus.

200

Kriteria Rujukan
Setelah dilakukan penatalaksanaan awal, pasien segera dirujuk ke dokter
mata.
Peralatan
1. Lup
2. Senter
3. Lidi kapas
Prognosis
1. Ad vitam
2. Ad functionam
3. Ad sanationam

: Bonam
: dubia
: dubia

Referensi
1. Karesh JW. The evaluation and management of eyelid trauma. Dalam :
Duane’s Clinical Ophthalmology, Volume 5. Philadelphia: Lippincott
Williams and Wilkins; 2006. (Karesh, 2006)
2. Ehlers JP, Shah CP, editors. The Wills Eye Manual-office and emergency
room diagnosis and treatment of eye disease. 5th edition. Philadelphia:
Lippincott Williams and Wilkins; 2008.
