---
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    collapsed: false
    smooth_scroll: true
    bullet_section: true
---

# Tuberkulosis Paru Dewasa

ICPC-2		: A70 *Tuberkulosis*  
ICD-10		: A15 *Respiratory tuberkulosis, bacteriologically and
histologically confirmed*  
**Kompetensi	: 4A**

***

## Masalah Kesehatan

Tuberkulosis (TB) adalah penyakit menular langsung yang disebabkan oleh kuman
TB yaitu *Mycobacterium tuberculosis*. Sebagian besar kuman TB menyerang paru,
namun dapat juga mengenai organ tubuh lainnya. Indonesia merupakan engara yang
termasuk sebagai 5 besar dari 22 negara di dunia dengan beban TB. Kontribiusi
TB di Indonesia sebesar 5,8%. Saat ini timbul kegawatdaruratan baru dalam
penanggulangan TB, yaitu TB Resisten Obat (*Multi Drug Resistance*/ MDR).

***

## *Subjective*

Suspek TB adalah seseorang dengan gejala atau tanda TB. Gejala umum TB Paru adalah batuk produktif lebih dari 2 minggu, yang disertai:

1. Gejala pernapasan (nyeri dada, sesak, napas, hemoptisis) dan/atau
2. Gejala sistemik (demam, tidak nafsu makan, penurunan berat badan, keringat
   malam dan mudah lelah) 

***

## *Objective*

### Pemeriksaan fisik

Kelainan pada TB Paru tergantung luas kelainan struktur paru. Pada awal
permulaan perkembangan penyakit umumnya sulit sekali menemukan kelainan. Pada
auskultasi terdengar suara napas bronkhial/amforik/ronkhi basah/suara napas
melemah di apex paru, tanda-tanda penarikan paru, diafragma, dan mediastinum.

***

### Pemeriksaan penunjang

1. Darah: limfositosis/ monositosis, LED meningkat, Hb turun.
2. Pemeriksaan mikroskopis kuman TB (Bakteri Tahan Asam/BTA) atau kultur kuman
   dari spesimen sputum/dahak sewaktu-pagi-sewaktu.
3. Untuk TB non paru, spesimen dapat diambil dari bilas lambung, cairan
   serebrospinal, cairan pleura ataupun biopsi jaringan.
4. Radiologi dengan foto toraks PA-Lateral/ top lordotik. Pada TB, umumnya di
   apeks paru terdapat gambaran bercak-bercak awan dengan batas yang tidak
   jelas atau bila dengan batas jelas membentuk tuberkuloma. Gambaran lain yang
   dapat menyertai yaitu, kavitas (bayangan berupa cincin berdinding tipis),
   pleuritis (penebalan pleura), efusi pleura (sudut kostrofenikus tumpul).

***

## *Assessment*

### Diagnosis pasti TB

Diagnosis ditegakkan berdasarkan anamnesis, pemeriksaan fisik dan pemeriksaan
penunjang (sputum untuk dewasa, tes tuberkulin pada anak).

### Kriteria diagnosis

Berdasarkan *International Standards for Tuberculosis Care* (ISTC 2014)

Standar Diagnosis

1. Untuk memastikan diagnosis lebih awal, petugas kesehatan harus waspada
   terhadap individu dan grup dengan faktor risiko TB dengan melakukan evaluasi
   klinis dan pemeriksaan diagnostik yang tepat pada mereka dengan gejala TB.
2. Semua pasien dengan batuk produktif yang berlangsung selama $$\geq$$ 2 minggu
   yang tidak jelas penyebabnya, harus dievaluasi untuk TB.
3. Semua pasien yang diduga menderita TB dan mampu mengeluarkan dahak, harus
   diperiksa mikroskopis spesimen apusan sputum/dahak minimal 2 kali atau
   1 spesimen sputum untuk pemeriksaan *Gen Xpert MTB/RIF*, yang diperiksa di
   laboratorium yang kualitasnya terjamin, salah satu diantaranya adalah
   spesimen pagi. Pasien dengan risiko resistensi obat, risiko HIV, atau sakit
   parah sebaiknya melakukan pemeriksaan *Gen Xpert MTB/RIF* sebagai uji diagnostik
   awal. Uji serologi darah dan *interferon-gamma release assay* sebaiknya
   tidak digunakan untuk mendiagnosis TB aktif.
4. Semua pasien yang diduga tuberkulosis ekstra paru, spesimen dari organ yang
   terlibat harus diperiksa secara mikrobiologis dan histologis. Uji *Gen Xpert
   MTB/RIF* direkomendasikan sebagai pilihan uji mikrobiologis untuk pasien
   terduga meningitis karena membutuhkan penegakkan diagnosis yang cepat.
5. Pasien terduga TB dengan apusan dahak engatif, sebaiknya dilakukan
   pemeriksaan *Gen Xpert MTB/RIF* dan/atau kultur dahak. Jika apusan dan uji *Gen Xpert
   MTB/RIF* negatif pada pasien dengan gejala klinins yang mendukung TB,
   sebeaiknya segera diberikan pengobatan anti tuberkulosis setelah pemeriksaan
   kultur.

***

## *Plan*

### Penatalaksanaan

Tujuan pengobatan:

1. Menyembuhkan, mengembalikan kualitas hidup dan produktivitas pasien.
1. Mencegah kematian akibat TB aktif atau efek lanjutan.
1. Mencegah kekambuhan TB.
1. Mengurangi penularan TB kepada orang lain.
1. Mencegah terjadinya resistensi obat dan penularannya.

### Prinsip-prinsip terapi:

1. Obat Anti Tuberkulosis (OAT) harus diberikan dalam bentuk kombinasi dari
   beberapa jenis obat, dalam jumlah cukup dan dosis tepat sesuai dengan
   kategri pengoabtan. Hindari penggunaan monoterapi.
1. Pemakaian OAT-Kombinasi Dosis Tepat (KDT) / *Fixed Dose Combination* (FDC)
   akan lebih menguntungkan dan dianjurkan
1. Obat ditelan sekaligus (*single dose*) dalam keadaan perut kosong.
1. Setiap praktisi yang mengobati pasien tuberkulosis mengembang tanggung jawab
   kesehatan masyarakat.
1. Semua pasien (termasuk mereka yang terinfeksi HIV) yang belum pernah diobati
   harus diberi paduan obat lini pertama.
1. Untuk menjamin kepatuhan pasien berobat hingga selesai, diperlukan suatu
   pendekatan yang berpihak kepada pasien (*patient centered approach*) dan
   dilakukan dengan pengawasan langsung (DOT = *directly observed treatment*)
   oleh seorang pengawas menelan obat.
1. Semua pasien harus dimonitor respons pengobatannya. Indikator penilaian
   terbaik adalah pemeriksaan dahak berkala yaitu pada akhir tahap awal, ulan
   ke-5 dana akhir pengobatan.
1. Rekaman tertulis tentang pengobatan, respons bakteriologis dan efek samping
   harus tercatat dan tersimpan. 

| Berat |                | Fase Intensif |             | Fase Lanjutan |           |
|-------|----------------|---------------|-------------|---------------|-----------|
| Badan | Harian         | Harian        | 3x/minggu   | Harian        | 3x/minggu |
|       | (R/H/Z/E)      | (R/H/Z)       | (R/H/Z)     | (R/H)         | (R/H)     |
|       | 150/75/400/275 | 150/75/40     | 150/150/500 | 150/75        | 150/150   |
| 30-37 | 2              | 2             | 2           | 2             | 2         |
| 38-54 | 3              | 3             | 3           | 3             | 3         |
| 55-70 | 4              | 4             | 4           | 4             | 4         |
| >71   | 5              | 5             | 5           | 5             | 5         |

**Tabel 1.1 Dosis obat antituberkulosis KDT/FDC**

|      | Rekomendasi dosis dalam mg/kgBB |                             |
|------|---------------------------------|-----------------------------|
| Obat | Harian                          | 3x seminggu                 |
| INH  | 5(4-6) max 300 mg/hr            | 10(8-12) max 900 mg/dosis   |
| RIF  | 10(8-12) max 600 mg/hr          | 10(8-12) max 600 mg/dosis   |
| PZA  | 25(20-30) max 1600 mg/hr        | 35(30-40) max 2500 mg/dosis |
| EMB  | 15(15-20) max 1600 mg/hr        | 30(25-35) max 2400 mg/dosis |

**Tabel 1.2 Dosis obat TB berdasarkan berat badan (BB)**

#### Tahapan pengobatan

Pengobatan TB diberikan dalam 2 tahap, yaitu tahap awal dan lanjutan

1. Tahap awal menggunakana paduan obat rifampisin, isoniazid, pirazinamid dan etambutol.
   * Pada tahap awal pasien mendapat tatalaksana yang terdiri dari 4 jenis obat
     (rifampisin, isoniazid, pirazinamid, dan etambutol), diminum setiap hari
     dan diawasi secara langsung untuk menjamin kepatuhan minum obat dan
     mencegah terjadinya kekebalan obat.
   * Bila pengobatan tahap awal diberikan secara adekuat daya penularan menurun
     dalam kurun waktu 2 minggu.
   * Pasien TB paru BTA psitif sebagain besar menjadi BTA negatif (konversi)
     setelah menyelesaikan pengobatan tahap awal. Setelah terjadi konversi
     pengobatan dilanjutkan dengan tahap lanjut
1. Tahap lanjutan menggunakan paduan obat rifampisin dan isoniazid.
   * Pada tahap lanjutan pasien mendapat 2 jenis obat (rifampisin dan
     isoniazid), namun dalam jangka waktu yang lebih lama (minimal 4 bulan). 
   * Obat dapat diminum secara intermitten yaitu 3x/minggu (obat program) atau
     tiap hari (obat non program)
   * Tahap lanjutan penting untuk membunuh kuman persisten sehingga mencegah
     terjadinya kekambuhan.

#### OAT lini pertama

Panduan OAT lini pertama yang digunakan oleh Program Nasional Pengendalian
Tuberkulosis di Indonesia adalah sebagai berikut:

1. Kategori 1: 2HRZE/4H3R3.  
   Artinya pengobatan tahap awal selama 2 bulan diberikan tiap hari dan tahap
   lanjutn selama 4 bulan diberikan 3 kali dalam semingu. Jadi lama pengobatan
   seluruhnya 6 bulan.
1. Kategori 2: 2HRZES/HRZE/5H3R3E3  
   Diberikan pada TB paru pengobatan ulang (TB kambuh, gagal pengobatan, putus
   berobat/*default*). Pada kategori 2, tahap awal pengobatan selama 3 bulan
   terdiri dari 2 bulan RHZE ditambah suntikan streptomisin, dan 1 bulan HRZE.
   Pengobatan tahap awal diberikan seiap hari. Tahap lanjutan diberikan HRE
   selama 5 bulan, 3 kali seminggu, Jadi lalma pengobatan 8 bulan.
1. OAT sisipan: HRZE  
   Apabila pemeriksaan dahak masih positif (belum konversi) pada akhir
   pengobatan tahap awal kategori 1 maupun kategori 2, maka diberikan
   pengobatan sisipan selama 1 bulan dengan HRZE.

#### Konseling dan Edukasi

1. Memberikan informasi kepada pasien dan keluarga tentang penyakit tuberkulosis.
1. Pengawasan ketaatan minum obat dan kontrol secara teratur.
1. Pola hidup sehat dan sanitasi lingkungan.

#### Kriteria Rujukan

1. Pasien dengan sputum BTA (-), klinis (+) tapi tidak menunjukkan perbaikan
   setelah pengobatan dalam jangka waktu tertentu.
1. Pasien dengan spsutum BTA (-), klinis (-/ meragukan).
1. Psien dengan sputum BTA tetap (+) setelah jangka waktu tertentu.
1. TB dengan komplikasi/keadaan khusus (TB dengan komorbid)
1. Suspek TB-MDR harus dirujuk ke pusat rujukan TB-MDR.

### Peralatan

1. Laboratorium untuk pemeriksan sputum, darah rutin.
1. Radiologi.
1. Uji *Gen Xpert-Rif* Mtb jika fasilitas tersedia.

## Prognosis

Prognosis pada umumnya baik apabila pasien melakukan terapi sesuai dengan
ketentuan pengobatan. Untuk TB dengan komorbid, prognosis menjadi kurang baik.

Kriteria hasil pengobatan:

1. Sembuh: pasien telah menyelesaikan pengobatannya secara lengkap dan
   pemeriksaan apusan dahak ulang (*follow up*), hasilnya negatif pada foto
   toraks AP dan pada satu pemeriksaan sebelumnya.
1. Pengobatan lengkap: pasien yang telah menyelesaikan pengobatannya secara
   lengkap tetapi tidak ada hasil pemeriksaan apusan dahak ulang pada foto
   toraks AP dan pada satu pemeriksaan sebelumnya.
1. Meninggal: pasien yang meninggal dalam masa pengobatan karena sebab apapun.
1. Putus berobat (*default*): pasien yang tidak berobat 2 bulan berturut-turut
   atau lebih sebelum masa pengobatannya selesai.
1. Gagal: Pasien yang hasil pemeriksaan dahaknya tetap positif atau kembali
   menjadi positif pada bulan ke lima atau selama pengobatan.
1. Pindah (*transfer out*): pasien yang dipindah ke unit pencatatan dan
   pelaporan (*register*) lain dan hasil pengobatannya tidak diketahui.
 
## Referensi

1. Perhimpunan Dokter Paru Indonesia. Tuberkulosis. PDPI. Jakarta. 2011.
   (Perhimpunan Dokter Paru Indonesia, 2011) 
1. Direktorat Jenderal Pengendalian Penyakit dan Penyehatan Lingkungan. Pedoman
   nasional pengendalian tuberkulosis. Jakarta: Kementerian Kesehatan RI. 2011.
   (Direktorat Jenderal Pengendalian Penyakit dan Penyehatan Lingkungan, 2011)
1. Panduan tata laksana tuberkulosis sesuai ISTC dengan strategi DOTS untuk
   praktik dokter swasta (DPS). Kementerian Kesehatan Republik Indonesia dan
   Ikatan Dokter Indonesia. Jakarta. 2012. (Kementerian Kesehatan Republik
   Indonesia, 2012)
1. Tuberculosis Coalition for Technical Assistance. International standards for
   tuberculosis care (ISTC). 3$$^{rd}$$ Ed. Tuberculosis Coalition for Technical
   Assistance. The Hague. 2014. (Tuberculosis Coalition for Technical
   Assistance, 2014)
1. Braunwald, E. Fauci, A.S. Kasper, D.L. Hauser, S.L. et al. Mycobacterial
   disease: Tuberculosis. Harrison's: principle of internal medicine. 17$$^{th}$$
   Ed. New York: McGraw-Hill Companies. 2009: hal. 1006-1020. (Braunwald, et
   al., 2009)
