---
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    collapsed: false
    smooth_scroll: true
    df_print: paged
  pdf_document:
    number_sections: true
    df_print: kable
    highlight: tango
  slidy_presentation:
    highlight: tango
csl: $HOME$/.pandoc/vancouver-superscript.csl
---

No. ICPC-2	: A94 *Perinatal morbidity other*  
No. ICD-10	: P38 *Omphalitis of newborn with or without mild haemorrhage*  
**Kompetensi	: 4A**

## Masalah Kesehatan

Tali pusat biasanya lepas pada hari ke-7 setelah lahir dan luka baru sembuh
pada hari ke-15. Infeksi pada tali pusat atau jaringan kulit di sekitar perlu
dikenali secara dini dalam rangka mencegah sepsis.

## *Subjective*

### Keluhan

Panas, rewel, tidak mau menyusu.

### Faktor risiko

1. Imunitas seluler dan humoral belum sempurna
2. Luka umbilikus
3. Kulit tipis sehingga mudah lecet

### Faktor predisposisi

Pemotongan dan perawatan tali pusat yang tidak steril

## *Objective*

### Pemeriksaan fisik

1. Ada tanda tanda infeksi di sekitar tali pusat seperti kemerahan, panas,
   bengkak, nyeri, dan mengeluarkan pus yang berbau busuk.
2. Infeksi tali pusat lokal atau terbatas: bila kemerahan dan bengkak terbatas
   pada daerah kurang dari 1cm di sekitar pangkal tali pusat.
3. Infeksi tali pusat berat atau meluas: bila kemerahan atau bengkak pada tali
   pusat meluas melebihi area 1 cm atau kulit di sekitar tali pusat bayi
   mengeras dan memerah serta bayi mengalami pembengkakan perut.
4. Tanda sistemik: demam, takikardia, hipotensi, letargi, somnolen, ikterus
   Pemeriksaan Penunjang: Penegakan Diagnostik(Assessment)

### Diagnosis klinis

Diagnosis ditegakkan berdasarkan anamnesis dan pemeriksaan fisik. Adanya
tanda-tanda infeksi di sekitar umblikus seperti bengkak, kemerahan dan
kekakuan. Pada keadaan tertentu ada lesi berbentuk impetigo bullosa.

### Diagnosis banding

1. Tali pusat normal dengan akumulasi cairan berbau busuk, tidak ada tanda
   tanda infeksi (pengobatan cukup dibersihkan dengan alkohol)

2. Granuloma-delayed epithelialization / Granuloma keterlambatan proses
   epitelisasi karena kauterisasi

### Komplikasi

1. Necrotizing fasciitis dengan tanda-tanda: edema, kulit tampak seperti jeruk
   (peau d’orange appearance) di sekitar tempat infeksi, progresivitas cepat
   dan dapat menyebabkan kematian maka kemungkinan menderita
2. Peritonitis
3. Trombosis vena porta
4. Abses

## *Plan*

### Penatalaksanaan

1. Perawatan lokal
   * Pembersihan tali pusat dengan menggunakan larutan antiseptik (Klorheksidin
     atau iodium povidon 2,5%) dengan kain kasa yang bersih delapan kali sehari
     sampai tidak ada nanah lagi pada tali pusat.
   * Setelah dibersihkan, tali pusat dioleskan dengan salep antibiotik 3-4 kali
     sehari.

2. Perawatan sistemik

Bila tanpa gejala sistemik, pasien diberikan antibiotik seperti kloksasilin
oral selama lima hari. Bila anak tampak sakit, harus dicek dahulu ada tidaknya
tanda-tanda sepsis. Anak dapat diberikan antibiotik kombinasi dengan
aminoglikosida. Bila tidak ada perbaikan, pertimbangkan kemungkinan Meticillin
Resistance Staphylococcus aureus (MRSA). Kontrol kembali bila tidak ada
perbaikan atau ada perluasan tanda-tanda infeksi dan komplikasi seperti bayi
panas, rewel dan mulai tak mau makan.

### Kriteria rujukan

1. Bila intake tidak mencukupi dan anak mulai tampak tanda dehidrasi
2. Terdapat tanda komplikasi sepsis

### Peralatan

Tidak diperlukan peralatan khusus untuk mendiagnosis penyakit infeksi pada
umbilikus.

## Prognosis

Prognosis jika pasien tidak mengalami komplikasi umumnya dubia ad bonam.

## Referensi

1. Ikatan Dokter Anak Indonesia. 2003. Infeksi Tali Pusat dalam Panduan
   Manajemen Masalah Bayi Baru Lahir. Jakarta. Departemen Kesehatan RI. (Ikatan
   Dokter Anak Indonesia, 2003)
2. Peadiatrics Clerkship University. The University of Chicago.
