---
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    collapsed: false
    smooth_scroll: true
    bullet_section: true
---

# Tuberkulosis Paru Dewasa

No ICPC-2	: A70 *Tuberkulosis*  
No ICD-10	: A15 *Respiratory tuberkulosis, bacteriologically and
histologically confirmed*  
**Kompetensi	: 4A**

***

## Masalah Kesehatan

Tuberkulosis (TB) adalah penyakit menular langsung yang disebabkan oleh kuman
TB yaitu *Mycobacterium tuberculosis*. Sebagian besar kuman TB menyerang paru,
namun dapat juga mengenai organ tubuh lainnya. Indonesia merupakan engara yang
termasuk sebagai 5 besar dari 22 negara di dunia dengan beban TB. Kontribiusi
TB di Indonesia sebesar 5,8%. Saat ini timbul kegawatdaruratan baru dalam
penanggulangan TB, yaitu TB Resisten Obat (*Multi Drug Resistance*/ MDR).

***

## Hasil Anamnesis (*Subjective*)

Suspek TB adalah seseorang dengan gejala atau tanda TB. Gejala umum TB Paru adalah batuk produktif lebih dari 2 minggu, yang disertai:

1. Gejala pernapasan (nyeri dada, sesak, napas, hemoptisis) dan/atau
2. Gejala sistemik (demam, tidak nafsu makan, penurunan berat badan, keringat
   malam dan mudah lelah) 

***

## Hasil Pemeriksaan Fisik dan Penunjang Sederhana (*Objective*) {.tabset .tabset-fade}

### Pemeriksaan Fisik

Kelainan pada TB Paru tergantung luas kelainan struktur paru. Pada awal
permulaan perkembangan penyakit umumnya sulit sekali menemukan kelainan. Pada
auskultasi terdengar suara napas bronkhial/amforik/ronkhi basah/suara napas
melemah di apex paru, tanda-tanda penarikan paru, diafragma, dan mediastinum.

***

### Pemeriksaan Penunjang

1. Darah: limfositosis/ monositosis, LED meningkat, Hb turun.
2. Pemeriksaan mikroskopis kuman TB (Bakteri Tahan Asam/BTA) atau kultur kuman
   dari spesimen sputum/dahak sewaktu-pagi-sewaktu.
3. Untuk TB non paru, spesimen dapat diambil dari bilas lambung, cairan
   serebrospinal, cairan pleura ataupun biopsi jaringan.
4. Radiologi dengan foto toraks PA-Lateral/ top lordotik. Pada TB, umumnya di
   apeks paru terdapat gambaran bercaka-bercak awan dengan batas yang tidak
   jelas atau bila dengan batas jelas membentuk tuberkuloma. Gambaran lain yang
   dapat menyertai yaitu, kavitas (bayangan berupa cincin berdinding tipis),
   pleuritis (penebalan pleura), efusi pleura (sudut kostrofenikus tumpul).

***

## Penegakkan Diagnosis (*Assessment*)

### Diagnosis Pasti TB

Diagnosis ditegakkan berdasarkan anamnesis, pemeriksaan fisis dan pemeriksaan
penunjang (sputum untuk dewasa, tes tuberkulin pada anak).

### Kriteria Diagnosis

Berdasarkan *International Standards for Tuberculosis Care* (ISTC 2014)

Standar Diagnosis

1. Untuk memastikan diagnosis lebih awal, petugas kesehatan harus waspada
   terhadap individu dan grup dengan faktor risiko TB dengan melakukan evaluasi
   klinis dan pemeriksaan diagnostik yang tepat pada mereka dengan gejala TB.
2. Semua pasien dengan batuk produktif yang berlangsung selama $\geq$ 2 minggu
   yang tidak jelas penyebabnya, harus dievaluasi untuk TB.
3. Semua pasien yang diduga menderita TB dan mampu mengeluarkan dahak, harus
   diperiksa mikroskopis spesimen apusan sputum/dahak minimal 2 kali atau
   1 spesimen sputum untuk pemeriksaan Xpert MTB/RIF*, yang diperiksa di
   laboratorium yang kualitasnya terjamin, salah satu diantaranya adalah
   spesimen pagi. Pasien dengan risiko resistensi obat, risiko HIV, atau sakit
   parah sebaiknya melakukan pemeriksaan Xpert MTB/RIF* sebagai uji diagnostik
   awal. Uji serologi darah dan *interferon-gamma release assay* sebaiknya
   tidak digunakan untuk mendiagnosis TB aktif.
4. Semua pasien yang diduga tuberkulosis ekstra paru, spesimen dari organ yang
   terlibat harus diperiksa secara mikrobiologis dan histologis. Uji Xpert
   MTB/RIF direkomendasikan sebagai pilihan uji mikrobiologis untuk pasien
   terduga meningitis karena membutuhkan penegakkan diagnosis yang cepat.
5. Pasien terduga TB dengan apusan dahak engatif, sebaiknya dilakukan
   pemeriksaan Xpert MTB/RIF dan/atau kultur dahak. Jika apusan dan uji Xpert
   MTB/RIF* negatif pada pasien dengan gejala klinins yang mendukung TB,
   sebeaiknya segera diberikan pengobatan anti tuberkulosis setelah pemeriksaan
   kultur.

***

## Penatalaksanaan Komprehensif (*Plan*)


